# Generated by Django 5.2.6 on 2025-09-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
