# Generated by Django 5.2.6 on 2025-09-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_postmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='description',
        ),
    ]
