# Generated by Django 5.2.6 on 2025-09-07 10:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_postmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
