# Generated by Django 5.2.6 on 2025-09-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutpagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagemodel',
            name='title',
        ),
    ]
